AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  rest-hour
  Sample SAM Template for rest-hour

Globals:
  Function:
    MemorySize: 128
    Handler: bootstrap
    Runtime: provided.al2023
    Timeout: 3
    Tracing: Active
    Environment:
      Variables:
        HOTELSTABLE_TABLE_NAME: !Ref HotelsTable
        HOTELSTABLE_TABLE_ARN: !GetAtt HotelsTable.Arn

Resources:
  HotelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  GetHotelsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_backend/hotels/get-hotels
      Events:
        RestHourApiGEThotels:
          Type: Api
          Properties:
            Path: /hotels
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HotelsTable
  GetHotelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_backend/hotel/get-hotel
      Events:
        RestHourApiGEThotel:
          Type: Api
          Properties:
            Path: /hotel
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HotelsTable
  PostHotelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_backend/hotel/post-hotel
      Events:
        RestHourApiPOSThotel:
          Type: Api
          Properties:
            Path: /hotel
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HotelsTable
  PutHotelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_backend/hotel/put-hotel
      Events:
        RestHourApiPUThotel:
          Type: Api
          Properties:
            Path: /hotel
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HotelsTable
  DeleteHotelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_backend/hotel/delete-hotel
      Events:
        RestHourApiDELETEhotel:
          Type: Api
          Properties:
            Path: /hotel
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HotelsTable

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  GetHotelsFunction:
    Description: Get Hotels Lambda Function ARN
    Value: !GetAtt GetHotelsFunction.Arn
  GetHotelFunction:
    Description: Get Hotel Lambda Function ARN
    Value: !GetAtt GetHotelFunction.Arn
  PostHotelFunction:
    Description: Post Hotel Lambda Function ARN
    Value: !GetAtt PostHotelFunction.Arn
  PutHotelFunction:
    Description: Put Hotel Lambda Function ARN
    Value: !GetAtt PutHotelFunction.Arn
  DeleteHotelFunction:
    Description: Delete Hotel Lambda Function ARN
    Value: !GetAtt DeleteHotelFunction.Arn

Metadata:
  AWS::Composer::Groups:
    Group:
      Label: Hotel Microservice
      Members:
        - GetHotelsFunction
        - GetHotelFunction
        - PostHotelFunction
        - PutHotelFunction
        - DeleteHotelFunction
        - HotelsTable